name: should-i-skate-today CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

#set environment variables 
env:
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  APP_NAME: ${{ 'should-i-skate-today' }}

jobs:
  build:
    
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build -c Release --no-restore

      - name: Test
        run: dotnet test -c Release --no-build --verbosity normal --filter "Category!=LongRunning" 
  deploy:
    name: Deploy to Heroku
    runs-on: ubuntu-latest
    needs: [build]
    steps:     
      # Clone the repository
      - name: Checkout
        uses: actions/checkout@v2
      
      # Build Docker image
      - name: Docker build
        run: docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
      
      # Push the Docker image to Heroku Container Registry
      - name: Publish
        run: |
          heroku container:push skate-today -a $APP_NAME
          heroku container:release skate-today -a $APP_NAME